spring:
  application:
    name: backend

battlenet:
  oauth:
    client-id: ${CLIENT-ID}
    client-secret: ${CLIENT-SECRET}
    token-url: https://oauth.battle.net/token

  wow-token:
    url: https://{region}.api.blizzard.com/data/wow/token/?namespace=dynamic-{region}