spring:
  application:
    name: backend

battlenet:
  oauth:
    token-uri: https://oauth.battle.net/token
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

wow:
  token:
    api:
      base-url: https://{region}.api.blizzard.com/data/wow/token/
      namespace: dynamic-{region}