spring:
  application:
    name: backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

battlenet:
  oauth:
    token-uri: https://oauth.battle.net/token
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

wow:
  token:
    api:
      base-url: https://{region}.api.blizzard.com/data/wow/token/
      namespace: dynamic-{region}